# auth-server:application.yml
# 端口
server:
  port: 8020
# 应用信息
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"

spring:
  application:
    name: "@project.name@"
  profiles:
    active: dev
  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://81.70.14.217:3306/hr?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  redis:
    host: 81.70.14.217
    port: 6379
    password: [370804sjr]
    database: 0
# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"