# webflux-learning
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
spring:
  application:
    name: "@project.name@"

  r2dbc:
    url: r2dbc:mysql://81.70.14.217:13306/hr?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: '[370804sjr]'
#logging:
#  level:
server:
  port: 8040
#    root: debug