# gateway：application.yml
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"

spring:
  application:
    name: "@project.name@"
  profiles:
    active: dev
  cloud:
    gateway:
      # 开启注册中心动态路由
      discovery:
        locator:
          enabled: true
      routes:
        - id: hr-manage
          uri: lb://hr-manage
          # uri: http://localhost:8010
          predicates:
            - Path=/api/**
        - id: without-auth
          uri: lb://hr-manage
          predicates:
            - Path=/without/api/**
          filters:
            - StripPrefix=1
        - id: auth-server
          uri: lb://auth-server
          # uri: http://localhost:8020
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: webfluxL
          uri: lb://webflux
          predicates:
            - Path=/f/**
          filters:
            - StripPrefix=1
  redis:
    host: 81.70.14.217
    port: 16379
    password: '[370804sjr]'
server:
  port: 8000

#logging:
#  level: