# gateway：application.yml
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"

spring:
  application:
    name: "@project.name@"
  profiles:
    active: dev
  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://81.70.14.217:13306/hr?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: '[370804sjr]'
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  cloud:
    gateway:
      # 开启注册中心动态路由
      discovery:
        locator:
          enabled: true
      routes:
        - id: hr-manage
          uri: lb://hr-manage
          # uri: http://localhost:8010
          predicates:
            - Path=/hr/**
          filters:
            - StripPrefix=1
        - id: without-auth
          uri: lb://hr-manage
          predicates:
            - Path=/without/api/**
          filters:
            - StripPrefix=2
        - id: auth-server
          uri: lb://auth-server
          # uri: http://localhost:8020
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: webfluxL
          uri: lb://webflux-learning
          predicates:
            - Path=/f/**
          filters:
            - StripPrefix=1
  redis:
    host: 81.70.14.217
    port: 16379
    password: '[370804sjr]'
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8020/rsa/publicKey'
server:
  port: 8000

#logging:
#  level: