server:
  port: 8000

spring:
  application:
    name: "@project.name@"
  profiles:
    active: dev

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://81.70.14.217:3306/hr?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"